# Note: Do not commit this file without first removing sensitive data (such as secrets)

name = "my-agent"
image = "my-repository/my-agent:0.1"

[config]
min_instances = 1
cpu = 1

[secrets]
[my-agent-secrets]
DAILY_API_KEY = ""
ELEVENLABS_API_KEY = ""
OPENAI_API_KEY = ""
